Allow feature functions with global variables
PotomacResearch/rescompy pull request #26
Opened 2022-10-10 15:30 UTC by nortondeclan

ESN.predict() routine updated to allow feature functions with global variables. This option is useful for e.g. storing the reservoir state of a second RC used as a model in the hybrid method, or for updating parameters of a non-stationary knowledge-based model.

PredictResult class updated to grant access to the reservoir states over the prediction period.

2022-10-14 17:06 UTC, andrew-pomerance requested changes
Line 1070: catch TypeError plus other error

2022-10-14 17:06 UTC, andrew-pomerance commented on rescompy/rescompy.py
> -        except TypeError:
except (TypeError, SomeOtherType):

2022-10-18 17:52 UTC, nortondeclan commented on rescompy/rescompy.py
> -        except TypeError:
Fixed with except(TypeError, numba.UnsupportedError).

2022-10-21 17:04 UTC, andrew-pomerance approved these changes

2022-10-21 17:04 UTC, merged